# NumPy cheatsheet

Copyright 2022 [MachineLearningMastery.com](https://machinelearningmastery.com/)

In [1]:
import numpy as np

## Ask for help

In [2]:
# This is a list of all numpy functions/submodules
print([x for x in dir(np) if x[0].islower()])

['abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'alen', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split', 'array_str', 'asanyarray', 'asarray', 'asarray_chkfinite', 'ascontiguousarray', 'asfarray', 'asfortranarray', 'asmatrix', 'asscalar', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'average', 'bartlett', 'base_repr', 'binary_repr', 'bincount', 'bitwise_and', 'bitwise_not', 'bitwise_or', 'bitwise_xor', 'blackman', 'block', 'bmat', 'bool8', 'bool_', 'broadcast', 'broadcast_arrays', 'broadcast_shapes', 'broadcast_to', 'busday_count', 'busday_offset', 'busdaycalendar', 'byte', 'byte_bounds', 'bytes0', 'bytes_', 'c_', 'can_cast', 'cast', 'cbrt', 'cdouble', 'ceil', 'cflo

In [3]:
# Print the docstring of numpy functions
np.info(np.where)

 where()

where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
--

## Generating array

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.asarray([1,2,3])

array([1, 2, 3])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((3,4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((3,4))

array([[0.29638547, 0.82859591, 0.07089721, 0.25944053],
       [0.32011999, 0.51136344, 0.5286878 , 0.83618863],
       [0.09762587, 0.10493056, 0.05519687, 0.59947369]])

In [13]:
np.random.randint(10, size=(3,4))

array([[7, 4, 5, 4],
       [2, 4, 2, 4],
       [1, 8, 8, 6]])

In [14]:
np.random.randn(3,4)  # note it is two arguments, not one tuple

array([[-1.13090119, -1.82672833, -1.46957454,  0.77323069],
       [-0.22906409,  1.73376918,  1.0887118 ,  0.02445698],
       [-0.16144862,  0.76866444, -1.22546744,  0.51423346]])

In [15]:
# create array of uninitialized values
np.empty((3,4))

array([[1.13090119, 1.82672833, 1.46957454, 0.77323069],
       [0.22906409, 1.73376918, 1.0887118 , 0.02445698],
       [0.16144862, 0.76866444, 1.22546744, 0.51423346]])

In [16]:
a = np.array([1,2])
b = np.array([3,4,5])
a,b

(array([1, 2]), array([3, 4, 5]))

In [17]:
np.meshgrid(a,b)

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[3, 3],
        [4, 4],
        [5, 5]])]

## Inspecting array

In [18]:
A = np.random.randn(3,4)

In [19]:
A.shape

(3, 4)

In [20]:
A.size # count of total elements

12

In [21]:
len(A) # axis 0 length

3

In [22]:
A.ndim # number of dimensions

2

In [23]:
A.dtype

dtype('float64')

In [24]:
A.astype(int)

array([[-1,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  1,  0]])

## Matrix multiplication / Vector dot-product

In [25]:
A = np.random.random((3,4))
B = np.random.randn(3,4)
A, B

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.91912902, 0.66852796, 0.36782425, 0.01194809]]),
 array([[ 0.96088413, -0.05353463,  0.66829372, -0.88898352],
        [ 0.8960371 ,  2.40403233,  0.08752414, -0.25952931],
        [-0.06254057,  1.63369261,  0.65843587,  1.05482128]]))

In [26]:
A @ B.T, np.matmul(A, B.T), np.dot(A, B.T)

(array([[ 0.23885996,  1.16429756,  1.01860057],
        [-0.26503643,  1.20476083,  2.25979497],
        [ 1.08258008,  2.45982915,  1.2894781 ]]),
 array([[ 0.23885996,  1.16429756,  1.01860057],
        [-0.26503643,  1.20476083,  2.25979497],
        [ 1.08258008,  2.45982915,  1.2894781 ]]),
 array([[ 0.23885996,  1.16429756,  1.01860057],
        [-0.26503643,  1.20476083,  2.25979497],
        [ 1.08258008,  2.45982915,  1.2894781 ]]))

In [27]:
A[0] @ B[0], np.matmul(A[0], B[0]), np.dot(A[0], B[0])

(0.23885995727188736, 0.23885995727188736, 0.23885995727188736)

## Element-wise operations

In [28]:
A + B, np.add(A,B)

(array([[ 1.62730162,  0.23338942,  0.76018565, -0.3855541 ],
        [ 0.89788343,  2.96594646,  0.81856104,  0.55631938],
        [ 0.85658845,  2.30222057,  1.02626012,  1.06676937]]),
 array([[ 1.62730162,  0.23338942,  0.76018565, -0.3855541 ],
        [ 0.89788343,  2.96594646,  0.81856104,  0.55631938],
        [ 0.85658845,  2.30222057,  1.02626012,  1.06676937]]))

In [29]:
A - B, np.subtract(A,B)

(array([[-0.29446664,  0.34045868, -0.57640179,  1.39241294],
        [-0.89419077, -1.84211821,  0.64351276,  1.07537801],
        [ 0.9816696 , -0.96516466, -0.29061162, -1.04287319]]),
 array([[-0.29446664,  0.34045868, -0.57640179,  1.39241294],
        [-0.89419077, -1.84211821,  0.64351276,  1.07537801],
        [ 0.9816696 , -0.96516466, -0.29061162, -1.04287319]]))

In [30]:
A * B, np.multiply(A,B)

(array([[ 0.64034999, -0.01536037,  0.0614108 , -0.44754046],
        [ 0.00165438,  1.35085973,  0.06398338, -0.21173665],
        [-0.05748286,  1.09216918,  0.24218868,  0.0126031 ]]),
 array([[ 0.64034999, -0.01536037,  0.0614108 , -0.44754046],
        [ 0.00165438,  1.35085973,  0.06398338, -0.21173665],
        [-0.05748286,  1.09216918,  0.24218868,  0.0126031 ]]))

In [31]:
A / B, np.divide(A, B)

(array([[ 6.93546150e-01, -5.35959693e+00,  1.37502308e-01,
         -5.66297811e-01],
        [ 2.06055038e-03,  2.33738173e-01,  8.35240303e+00,
         -3.14357050e+00],
        [-1.46965236e+01,  4.09212817e-01,  5.58633374e-01,
          1.13271220e-02]]),
 array([[ 6.93546150e-01, -5.35959693e+00,  1.37502308e-01,
         -5.66297811e-01],
        [ 2.06055038e-03,  2.33738173e-01,  8.35240303e+00,
         -3.14357050e+00],
        [-1.46965236e+01,  4.09212817e-01,  5.58633374e-01,
          1.13271220e-02]]))

In [32]:
A // B, np.floor_divide(A, B)

(array([[  0.,  -6.,   0.,  -1.],
        [  0.,   0.,   8.,  -4.],
        [-15.,   0.,   0.,   0.]]),
 array([[  0.,  -6.,   0.,  -1.],
        [  0.,   0.,   8.,  -4.],
        [-15.,   0.,   0.,   0.]]))

In [33]:
A % B, np.mod(A, B)

(array([[ 0.66641749, -0.03428374,  0.09189193, -0.3855541 ],
        [ 0.00184633,  0.56191413,  0.03084377, -0.22226856],
        [-0.01897959,  0.66852796,  0.36782425,  0.01194809]]),
 array([[ 0.66641749, -0.03428374,  0.09189193, -0.3855541 ],
        [ 0.00184633,  0.56191413,  0.03084377, -0.22226856],
        [-0.01897959,  0.66852796,  0.36782425,  0.01194809]]))

In [34]:
# compare entire array
np.array_equal(A, B)

False

In [35]:
A ** B, np.power(A, B)

(array([[0.67708111, 1.06912441, 0.20284522, 1.84065197],
        [0.00355232, 0.25014882, 0.97295198, 1.05424098],
        [1.0052879 , 0.51796348, 0.51760925, 0.00937332]]),
 array([[0.67708111, 1.06912441, 0.20284522, 1.84065197],
        [0.00355232, 0.25014882, 0.97295198, 1.05424098],
        [1.0052879 , 0.51796348, 0.51760925, 0.00937332]]))

In [36]:
A == B, np.equal(A,B)

(array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]),
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]))

In [37]:
A != B, np.not_equal(A,B)

(array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

In [38]:
A > B, np.greater(A,B)

(array([[False,  True, False,  True],
        [False, False,  True,  True],
        [ True, False, False, False]]),
 array([[False,  True, False,  True],
        [False, False,  True,  True],
        [ True, False, False, False]]))

In [39]:
A >= B, np.greater_equal(A,B)

(array([[False,  True, False,  True],
        [False, False,  True,  True],
        [ True, False, False, False]]),
 array([[False,  True, False,  True],
        [False, False,  True,  True],
        [ True, False, False, False]]))

In [40]:
A < B, np.less(A,B)

(array([[ True, False,  True, False],
        [ True,  True, False, False],
        [False,  True,  True,  True]]),
 array([[ True, False,  True, False],
        [ True,  True, False, False],
        [False,  True,  True,  True]]))

In [41]:
A <= B, np.less_equal(A,B)

(array([[ True, False,  True, False],
        [ True,  True, False, False],
        [False,  True,  True,  True]]),
 array([[ True, False,  True, False],
        [ True,  True, False, False],
        [False,  True,  True,  True]]))

In [42]:
np.exp(B)

array([[ 2.61400658,  0.94787311,  1.95090568,  0.41107339],
       [ 2.44987524, 11.06771522,  1.09146861,  0.77141459],
       [ 0.93937495,  5.12275618,  1.93176843,  2.87146191]])

In [43]:
np.power(2,B)

array([[1.94650241, 0.96357266, 1.58919231, 0.53999445],
       [1.86094717, 5.29280437, 1.06254515, 0.83536042],
       [0.95757635, 3.10306219, 1.57837047, 2.07746083]])

In [44]:
np.power(B,3)

array([[ 8.87182701e-01, -1.53427943e-04,  2.98470996e-01,
        -7.02556299e-01],
       [ 7.19412498e-01,  1.38937958e+01,  6.70476524e-04,
        -1.74807176e-02],
       [-2.44616412e-04,  4.36024642e+00,  2.85456833e-01,
         1.17364471e+00]])

In [45]:
np.log(A)

array([[-0.40583894, -1.24853774, -2.38714208, -0.68631175],
       [-6.29455562, -0.57640624, -0.31329134, -0.20352636],
       [-0.08432877, -0.40267707, -1.00015004, -4.42718391]])

In [46]:
np.log10(A)

array([[-0.17625361, -0.54223305, -1.03672263, -0.29806141],
       [-2.73369077, -0.25033005, -0.1360607 , -0.08839038],
       [-0.03662352, -0.17488043, -0.43435964, -1.92270154]])

In [47]:
np.log2(A)

array([[-0.58550183, -1.8012592 , -3.44391804, -0.99013856],
       [-9.08112417, -0.83157843, -0.45198386, -0.29362647],
       [-0.1216607 , -0.58094021, -1.4429115 , -6.38707627]])

In [48]:
np.square(A)

array([[4.44112271e-01, 8.23254099e-02, 8.44412659e-03, 2.53441183e-01],
       [3.40893295e-06, 3.15747485e-01, 5.34414953e-01, 6.65609096e-01],
       [8.44798160e-01, 4.46929627e-01, 1.35294679e-01, 1.42756837e-04]])

In [49]:
np.sqrt(A)

array([[0.81634398, 0.53565292, 0.30313682, 0.7095276 ],
       [0.04296894, 0.74960932, 0.85500696, 0.90324343],
       [0.95871217, 0.81763559, 0.60648516, 0.10930732]])

In [50]:
np.cbrt(A)

array([[0.87347161, 0.65956204, 0.45125891, 0.79551102],
       [0.12267886, 0.82519512, 0.90083745, 0.93440799],
       [0.97228181, 0.8743927 , 0.71649548, 0.22861224]])

In [51]:
np.sin(A), np.cos(A), np.tan(A)

(array([[0.61817396, 0.28300337, 0.09176266, 0.48243231],
        [0.00184633, 0.53280698, 0.66764195, 0.72830743],
        [0.79507366, 0.61983149, 0.35958607, 0.0119478 ]]),
 array([[0.78604132, 0.95911892, 0.99578091, 0.87593325],
        [0.9999983 , 0.8462368 , 0.74448252, 0.68525053],
        [0.60651288, 0.78473494, 0.93311192, 0.99992862]]),
 array([[0.78643952, 0.29506598, 0.09215145, 0.55076379],
        [0.00184633, 0.62961925, 0.8967866 , 1.06283381],
        [1.31089329, 0.78986097, 0.3853622 , 0.01194866]]))

In [52]:
np.arcsin(A), np.arccos(A), np.arctan(A)

(array([[0.7293934 , 0.29101433, 0.09202175, 0.52756328],
        [0.00184633, 0.59669798, 0.81984035, 0.95419534],
        [1.16586391, 0.73222763, 0.37666816, 0.01194837]]),
 array([[0.84140293, 1.279782  , 1.47877458, 1.04323305],
        [1.56895   , 0.97409835, 0.75095598, 0.61660099],
        [0.40493242, 0.83856869, 1.19412817, 1.55884795]]),
 array([[0.58783008, 0.27941776, 0.09163458, 0.46638738],
        [0.00184633, 0.51194429, 0.63125386, 0.68433035],
        [0.74328366, 0.58929008, 0.35246481, 0.01194752]]))

In [53]:
np.abs(B), np.sign(B)

(array([[0.96088413, 0.05353463, 0.66829372, 0.88898352],
        [0.8960371 , 2.40403233, 0.08752414, 0.25952931],
        [0.06254057, 1.63369261, 0.65843587, 1.05482128]]),
 array([[ 1., -1.,  1., -1.],
        [ 1.,  1.,  1., -1.],
        [-1.,  1.,  1.,  1.]]))

In [54]:
C = np.array([
    [0.1, np.inf, np.nan, 0.0],
    [-np.inf, np.nan, -2.1, 0.1]
])
C

array([[ 0.1,  inf,  nan,  0. ],
       [-inf,  nan, -2.1,  0.1]])

In [55]:
np.isnan(C), np.isinf(C), np.isposinf(C), np.isneginf(C)

(array([[False, False,  True, False],
        [False,  True, False, False]]),
 array([[False,  True, False, False],
        [ True, False, False, False]]),
 array([[False,  True, False, False],
        [False, False, False, False]]),
 array([[False, False, False, False],
        [ True, False, False, False]]))

In [56]:
np.ceil(B), np.floor(B), np.round(B, 2)

(array([[ 1., -0.,  1., -0.],
        [ 1.,  3.,  1., -0.],
        [-0.,  2.,  1.,  2.]]),
 array([[ 0., -1.,  0., -1.],
        [ 0.,  2.,  0., -1.],
        [-1.,  1.,  0.,  1.]]),
 array([[ 0.96, -0.05,  0.67, -0.89],
        [ 0.9 ,  2.4 ,  0.09, -0.26],
        [-0.06,  1.63,  0.66,  1.05]]))

In [57]:
np.clip(A, 0.2, 0.8)

array([[0.66641749, 0.28692405, 0.2       , 0.50342942],
       [0.2       , 0.56191413, 0.7310369 , 0.8       ],
       [0.8       , 0.66852796, 0.36782425, 0.2       ]])

## Aggregate functions

In [58]:
A.mean(), A.std(), np.median(A)

(0.4688948551530219, 0.30178835484292116, 0.5326717738114577)

In [59]:
A.mean(axis=0), A.std(axis=1), np.median(A, axis=0)

(array([0.52913095, 0.50578871, 0.39691769, 0.44374207]),
 array([0.21721752, 0.31704426, 0.33892134]),
 array([0.66641749, 0.56191413, 0.36782425, 0.50342942]))

In [60]:
np.corrcoef(A[0],B[0])

array([[ 1.       , -0.0434439],
       [-0.0434439,  1.       ]])

In [61]:
np.corrcoef(A)

array([[ 1.        , -0.64186263,  0.2799331 ],
       [-0.64186263,  1.        , -0.88909396],
       [ 0.2799331 , -0.88909396,  1.        ]])

In [62]:
A > B

array([[False,  True, False,  True],
       [False, False,  True,  True],
       [ True, False, False, False]])

In [63]:
(A > B).all(), (A > B).any() # if numeric, non-zero is True

(False, True)

In [64]:
(A > B).all(axis=0), (A > B).any(axis=0)

(array([False, False, False, False]), array([ True,  True,  True,  True]))

In [65]:
A.sum(axis=0), A.sum(axis=1), A.sum()

(array([1.58739284, 1.51736613, 1.19075308, 1.33122621]),
 array([1.54866289, 2.11064606, 1.96742932]),
 5.626738261836263)

In [66]:
A.prod(axis=0), A.prod(axis=1), A.prod()

(array([0.00113092, 0.10778454, 0.02470911, 0.00490735]),
 array([0.00884564, 0.00061877, 0.00270044]),
 1.4780607086567297e-08)

In [67]:
A.min(axis=0), A.min(axis=1), A.min()

(array([0.00184633, 0.28692405, 0.09189193, 0.01194809]),
 array([0.09189193, 0.00184633, 0.01194809]),
 0.0018463295897631626)

In [68]:
A.max(axis=0), A.max(axis=1), A.max()

(array([0.91912902, 0.66852796, 0.7310369 , 0.8158487 ]),
 array([0.66641749, 0.8158487 , 0.91912902]),
 0.9191290223483035)

In [69]:
A.argmin(axis=0), A.argmin(axis=1), A.argmin()

(array([1, 0, 0, 2]), array([2, 0, 3]), 4)

In [70]:
A, A[A.argmin(axis=0),np.arange(A.shape[1])], A[np.arange(A.shape[0]),A.argmin(axis=1)]

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.91912902, 0.66852796, 0.36782425, 0.01194809]]),
 array([0.00184633, 0.28692405, 0.09189193, 0.01194809]),
 array([0.09189193, 0.00184633, 0.01194809]))

In [71]:
A.argmax(axis=0), A.argmax(axis=1), A.argmax()

(array([2, 2, 1, 1]), array([0, 3, 0]), 8)

In [72]:
A, A[A.argmax(axis=0),np.arange(A.shape[1])], A[np.arange(A.shape[0]),A.argmax(axis=1)]

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.91912902, 0.66852796, 0.36782425, 0.01194809]]),
 array([0.91912902, 0.66852796, 0.7310369 , 0.8158487 ]),
 array([0.66641749, 0.8158487 , 0.91912902]))

In [73]:
A.cumsum(axis=0), A.cumsum(axis=1), A.cumsum()

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.66826382, 0.84883818, 0.82292883, 1.31927812],
        [1.58739284, 1.51736613, 1.19075308, 1.33122621]]),
 array([[6.66417490e-01, 9.53341539e-01, 1.04523347e+00, 1.54866289e+00],
        [1.84632959e-03, 5.63760456e-01, 1.29479736e+00, 2.11064606e+00],
        [9.19129022e-01, 1.58765698e+00, 1.95548123e+00, 1.96742932e+00]]),
 array([0.66641749, 0.95334154, 1.04523347, 1.54866289, 1.55050922,
        2.11242335, 2.84346025, 3.65930894, 4.57843797, 5.24696592,
        5.61479017, 5.62673826]))

In [74]:
A.cumprod(axis=0), A.cumprod(axis=1), A.cumprod()

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.00123043, 0.16122668, 0.06717639, 0.41072224],
        [0.00113092, 0.10778454, 0.02470911, 0.00490735]]),
 array([[6.66417490e-01, 1.91211205e-01, 1.75707664e-02, 8.84564077e-03],
        [1.84632959e-03, 1.03747868e-03, 7.58435199e-04, 6.18768369e-04],
        [9.19129022e-01, 6.14463446e-01, 2.26014556e-01, 2.70044209e-03]]),
 array([6.66417490e-01, 1.91211205e-01, 1.75707664e-02, 8.84564077e-03,
        1.63319683e-05, 9.17716369e-06, 6.70884532e-06, 5.47340271e-06,
        5.03076328e-06, 3.36320589e-06, 1.23706869e-06, 1.47806071e-08]))

# Slicing

In [75]:
A, A[2], A[2:3], A[2:3, 1:3]

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.91912902, 0.66852796, 0.36782425, 0.01194809]]),
 array([0.91912902, 0.66852796, 0.36782425, 0.01194809]),
 array([[0.91912902, 0.66852796, 0.36782425, 0.01194809]]),
 array([[0.66852796, 0.36782425]]))

In [76]:
A[2, 1:3], A[2][1:3]

(array([0.66852796, 0.36782425]), array([0.66852796, 0.36782425]))

In [77]:
C = np.random.random((2,3,3,4))
C[0:1,...,3]

array([[[0.51400259, 0.73219596, 0.21201768],
        [0.36296938, 0.36091564, 0.33484285],
        [0.93708761, 0.7382183 , 0.62752974]]])

In [78]:
# Boolean indexing
B > 0.5, B.sum(axis=0) > 2

(array([[ True, False,  True, False],
        [ True,  True, False, False],
        [False,  True,  True,  True]]),
 array([False,  True, False, False]))

In [79]:
A[B > 0.5], A[:, B.sum(axis=0) > 2]

(array([0.66641749, 0.09189193, 0.00184633, 0.56191413, 0.66852796,
        0.36782425, 0.01194809]),
 array([[0.28692405],
        [0.56191413],
        [0.66852796]]))

In [80]:
# Fancy indexing
A[:, [0,1,0,0,1]]

array([[0.66641749, 0.28692405, 0.66641749, 0.66641749, 0.28692405],
       [0.00184633, 0.56191413, 0.00184633, 0.00184633, 0.56191413],
       [0.91912902, 0.66852796, 0.91912902, 0.91912902, 0.66852796]])

In [81]:
A[[0,1,0], [2,3,3]] # indices must match in length, this produces A[0,2], A[1,3], A[0,3]

array([0.09189193, 0.8158487 , 0.50342942])

In [82]:
np.where(A>B, A, B) # pick elements from A if condition is True, else B

array([[0.96088413, 0.28692405, 0.66829372, 0.50342942],
       [0.8960371 , 2.40403233, 0.7310369 , 0.8158487 ],
       [0.91912902, 1.63369261, 0.65843587, 1.05482128]])

In [83]:
B

array([[ 0.96088413, -0.05353463,  0.66829372, -0.88898352],
       [ 0.8960371 ,  2.40403233,  0.08752414, -0.25952931],
       [-0.06254057,  1.63369261,  0.65843587,  1.05482128]])

In [84]:
np.clip(B, 0.1, 0.9),\
np.select([B < 0.1, B > 0.9], [0.1, 0.9], B), \
np.where(B>0.1, np.where(B<0.9, B, 0.9), 0.1) # same as clip

(array([[0.9       , 0.1       , 0.66829372, 0.1       ],
        [0.8960371 , 0.9       , 0.1       , 0.1       ],
        [0.1       , 0.9       , 0.65843587, 0.9       ]]),
 array([[0.9       , 0.1       , 0.66829372, 0.1       ],
        [0.8960371 , 0.9       , 0.1       , 0.1       ],
        [0.1       , 0.9       , 0.65843587, 0.9       ]]),
 array([[0.9       , 0.1       , 0.66829372, 0.1       ],
        [0.8960371 , 0.9       , 0.1       , 0.1       ],
        [0.1       , 0.9       , 0.65843587, 0.9       ]]))

In [85]:
np.select([(B > 0.1) & (B < 0.9), (B >= 0.5) & (B < 0.9)], [0.1, 0.9], B)

array([[ 0.96088413, -0.05353463,  0.1       , -0.88898352],
       [ 0.1       ,  2.40403233,  0.08752414, -0.25952931],
       [-0.06254057,  1.63369261,  0.1       ,  1.05482128]])

## Transforming arrays

In [86]:
Z = A.copy()
Z = np.copy(A)

In [87]:
np.unique(A)

array([0.00184633, 0.01194809, 0.09189193, 0.28692405, 0.36782425,
       0.50342942, 0.56191413, 0.66641749, 0.66852796, 0.7310369 ,
       0.8158487 , 0.91912902])

In [88]:
np.sort(A), np.sort(A,axis=0), np.sort(A,axis=1)

(array([[0.09189193, 0.28692405, 0.50342942, 0.66641749],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.01194809, 0.36782425, 0.66852796, 0.91912902]]),
 array([[0.00184633, 0.28692405, 0.09189193, 0.01194809],
        [0.66641749, 0.56191413, 0.36782425, 0.50342942],
        [0.91912902, 0.66852796, 0.7310369 , 0.8158487 ]]),
 array([[0.09189193, 0.28692405, 0.50342942, 0.66641749],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.01194809, 0.36782425, 0.66852796, 0.91912902]]))

In [89]:
A.sort() # sort on each row in-place
A

array([[0.09189193, 0.28692405, 0.50342942, 0.66641749],
       [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
       [0.01194809, 0.36782425, 0.66852796, 0.91912902]])

In [90]:
A.sort(axis=0) # sort on each column in-place
A

array([[0.00184633, 0.28692405, 0.50342942, 0.66641749],
       [0.01194809, 0.36782425, 0.66852796, 0.8158487 ],
       [0.09189193, 0.56191413, 0.7310369 , 0.91912902]])

In [91]:
Z.argsort() # return index to sort

array([[2, 1, 3, 0],
       [0, 1, 2, 3],
       [3, 2, 1, 0]])

In [92]:
Z.argsort(axis=0), Z.argsort(axis=1)

(array([[1, 0, 0, 2],
        [0, 1, 2, 0],
        [2, 2, 1, 1]]),
 array([[2, 1, 3, 0],
        [0, 1, 2, 3],
        [3, 2, 1, 0]]))

In [93]:
Z[[[0],[1],[2]], Z.argsort()]

array([[0.09189193, 0.28692405, 0.50342942, 0.66641749],
       [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
       [0.01194809, 0.36782425, 0.66852796, 0.91912902]])

In [94]:
Z, Z.T, Z.swapaxes(0,1), np.transpose(Z)

(array([[0.66641749, 0.28692405, 0.09189193, 0.50342942],
        [0.00184633, 0.56191413, 0.7310369 , 0.8158487 ],
        [0.91912902, 0.66852796, 0.36782425, 0.01194809]]),
 array([[0.66641749, 0.00184633, 0.91912902],
        [0.28692405, 0.56191413, 0.66852796],
        [0.09189193, 0.7310369 , 0.36782425],
        [0.50342942, 0.8158487 , 0.01194809]]),
 array([[0.66641749, 0.00184633, 0.91912902],
        [0.28692405, 0.56191413, 0.66852796],
        [0.09189193, 0.7310369 , 0.36782425],
        [0.50342942, 0.8158487 , 0.01194809]]),
 array([[0.66641749, 0.00184633, 0.91912902],
        [0.28692405, 0.56191413, 0.66852796],
        [0.09189193, 0.7310369 , 0.36782425],
        [0.50342942, 0.8158487 , 0.01194809]]))

In [95]:
Z.ravel(), Z.reshape(-1)

(array([0.66641749, 0.28692405, 0.09189193, 0.50342942, 0.00184633,
        0.56191413, 0.7310369 , 0.8158487 , 0.91912902, 0.66852796,
        0.36782425, 0.01194809]),
 array([0.66641749, 0.28692405, 0.09189193, 0.50342942, 0.00184633,
        0.56191413, 0.7310369 , 0.8158487 , 0.91912902, 0.66852796,
        0.36782425, 0.01194809]))

In [96]:
Z.reshape(3,2,2)

array([[[0.66641749, 0.28692405],
        [0.09189193, 0.50342942]],

       [[0.00184633, 0.56191413],
        [0.7310369 , 0.8158487 ]],

       [[0.91912902, 0.66852796],
        [0.36782425, 0.01194809]]])

In [97]:
np.expand_dims(Z, 2)

array([[[0.66641749],
        [0.28692405],
        [0.09189193],
        [0.50342942]],

       [[0.00184633],
        [0.56191413],
        [0.7310369 ],
        [0.8158487 ]],

       [[0.91912902],
        [0.66852796],
        [0.36782425],
        [0.01194809]]])

In [98]:
np.resize(Z, (2,2))

array([[0.66641749, 0.28692405],
       [0.09189193, 0.50342942]])

In [99]:
np.resize(Z[:1], (3,3)) # repetitively fill in a new array

array([[0.66641749, 0.28692405, 0.09189193],
       [0.50342942, 0.66641749, 0.28692405],
       [0.09189193, 0.50342942, 0.66641749]])

In [100]:
np.pad(A,2)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00184633, 0.28692405, 0.50342942,
        0.66641749, 0.        , 0.        ],
       [0.        , 0.        , 0.01194809, 0.36782425, 0.66852796,
        0.8158487 , 0.        , 0.        ],
       [0.        , 0.        , 0.09189193, 0.56191413, 0.7310369 ,
        0.91912902, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [101]:
np.pad(A, 1, "constant", constant_values=[[-1,0],[1,2]])

array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00,
        -1.00000000e+00, -1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  1.84632959e-03,  2.86924049e-01,
         5.03429422e-01,  6.66417490e-01,  2.00000000e+00],
       [ 1.00000000e+00,  1.19480893e-02,  3.67824250e-01,
         6.68527955e-01,  8.15848697e-01,  2.00000000e+00],
       [ 1.00000000e+00,  9.18919289e-02,  5.61914126e-01,
         7.31036903e-01,  9.19129022e-01,  2.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00]])

In [102]:
np.append(A,B) # flatten and append

array([ 1.84632959e-03,  2.86924049e-01,  5.03429422e-01,  6.66417490e-01,
        1.19480893e-02,  3.67824250e-01,  6.68527955e-01,  8.15848697e-01,
        9.18919289e-02,  5.61914126e-01,  7.31036903e-01,  9.19129022e-01,
        9.60884132e-01, -5.35346319e-02,  6.68293717e-01, -8.88983521e-01,
        8.96037102e-01,  2.40403233e+00,  8.75241413e-02, -2.59529314e-01,
       -6.25405741e-02,  1.63369261e+00,  6.58435868e-01,  1.05482128e+00])

In [103]:
np.vstack((A,B)), np.r_[A,B], np.concatenate((A,B), axis=0), np.append(A, B, axis=0)

(array([[ 1.84632959e-03,  2.86924049e-01,  5.03429422e-01,
          6.66417490e-01],
        [ 1.19480893e-02,  3.67824250e-01,  6.68527955e-01,
          8.15848697e-01],
        [ 9.18919289e-02,  5.61914126e-01,  7.31036903e-01,
          9.19129022e-01],
        [ 9.60884132e-01, -5.35346319e-02,  6.68293717e-01,
         -8.88983521e-01],
        [ 8.96037102e-01,  2.40403233e+00,  8.75241413e-02,
         -2.59529314e-01],
        [-6.25405741e-02,  1.63369261e+00,  6.58435868e-01,
          1.05482128e+00]]),
 array([[ 1.84632959e-03,  2.86924049e-01,  5.03429422e-01,
          6.66417490e-01],
        [ 1.19480893e-02,  3.67824250e-01,  6.68527955e-01,
          8.15848697e-01],
        [ 9.18919289e-02,  5.61914126e-01,  7.31036903e-01,
          9.19129022e-01],
        [ 9.60884132e-01, -5.35346319e-02,  6.68293717e-01,
         -8.88983521e-01],
        [ 8.96037102e-01,  2.40403233e+00,  8.75241413e-02,
         -2.59529314e-01],
        [-6.25405741e-02,  1.63369261e+00

In [104]:
np.hstack((A,B)), np.c_[A,B], np.concatenate((A,B), axis=1), np.append(A, B, axis=1)

(array([[ 1.84632959e-03,  2.86924049e-01,  5.03429422e-01,
          6.66417490e-01,  9.60884132e-01, -5.35346319e-02,
          6.68293717e-01, -8.88983521e-01],
        [ 1.19480893e-02,  3.67824250e-01,  6.68527955e-01,
          8.15848697e-01,  8.96037102e-01,  2.40403233e+00,
          8.75241413e-02, -2.59529314e-01],
        [ 9.18919289e-02,  5.61914126e-01,  7.31036903e-01,
          9.19129022e-01, -6.25405741e-02,  1.63369261e+00,
          6.58435868e-01,  1.05482128e+00]]),
 array([[ 1.84632959e-03,  2.86924049e-01,  5.03429422e-01,
          6.66417490e-01,  9.60884132e-01, -5.35346319e-02,
          6.68293717e-01, -8.88983521e-01],
        [ 1.19480893e-02,  3.67824250e-01,  6.68527955e-01,
          8.15848697e-01,  8.96037102e-01,  2.40403233e+00,
          8.75241413e-02, -2.59529314e-01],
        [ 9.18919289e-02,  5.61914126e-01,  7.31036903e-01,
          9.19129022e-01, -6.25405741e-02,  1.63369261e+00,
          6.58435868e-01,  1.05482128e+00]]),
 array([[ 1.

In [105]:
np.insert(A, 2, 0.5)

array([0.00184633, 0.28692405, 0.5       , 0.50342942, 0.66641749,
       0.01194809, 0.36782425, 0.66852796, 0.8158487 , 0.09189193,
       0.56191413, 0.7310369 , 0.91912902])

In [106]:
np.insert(A, 2, 0.5, axis=1)

array([[0.00184633, 0.28692405, 0.5       , 0.50342942, 0.66641749],
       [0.01194809, 0.36782425, 0.5       , 0.66852796, 0.8158487 ],
       [0.09189193, 0.56191413, 0.5       , 0.7310369 , 0.91912902]])

In [107]:
Z[:, 2:3] = 0.5
Z

array([[0.66641749, 0.28692405, 0.5       , 0.50342942],
       [0.00184633, 0.56191413, 0.5       , 0.8158487 ],
       [0.91912902, 0.66852796, 0.5       , 0.01194809]])

In [108]:
Z[:, 2] = 0.4
Z

array([[0.66641749, 0.28692405, 0.4       , 0.50342942],
       [0.00184633, 0.56191413, 0.4       , 0.8158487 ],
       [0.91912902, 0.66852796, 0.4       , 0.01194809]])

In [109]:
np.delete(Z, 2, axis=1)

array([[0.66641749, 0.28692405, 0.50342942],
       [0.00184633, 0.56191413, 0.8158487 ],
       [0.91912902, 0.66852796, 0.01194809]])

In [110]:
np.delete(Z, [2,3], axis=1)

array([[0.66641749, 0.28692405],
       [0.00184633, 0.56191413],
       [0.91912902, 0.66852796]])

In [111]:
np.hsplit(A, 2) # split array into horizontal two of equal shapes

[array([[0.00184633, 0.28692405],
        [0.01194809, 0.36782425],
        [0.09189193, 0.56191413]]),
 array([[0.50342942, 0.66641749],
        [0.66852796, 0.8158487 ],
        [0.7310369 , 0.91912902]])]

In [112]:
np.vsplit(A, 3) # split array into vertical 3 of equal shapes

[array([[0.00184633, 0.28692405, 0.50342942, 0.66641749]]),
 array([[0.01194809, 0.36782425, 0.66852796, 0.8158487 ]]),
 array([[0.09189193, 0.56191413, 0.7310369 , 0.91912902]])]

## Linear Algebra functions

In [113]:
np.linalg.pinv(A)

array([[ -5.14253269,   0.86244485,   2.76914077],
       [ -0.60972356,  -5.00897377,   4.99178291],
       [-22.29874613,  20.58075818,  -2.0972416 ],
       [ 18.62238644, -13.39304061,  -0.57255728]])

In [114]:
M = A @ A.T
M

array([[0.77988227, 0.98581217, 1.14194548],
       [0.98581217, 1.24797616, 1.4463724 ],
       [1.14194548, 1.4463724 , 1.70340472]])

In [115]:
np.linalg.det(M)

3.8830545618760194e-05

In [116]:
np.linalg.inv(M)

array([[ 870.84476126, -709.71654142,   18.81947055],
       [-709.71654142,  628.77477364,  -58.11001779],
       [  18.81947055,  -58.11001779,   37.31228134]])

In [117]:
np.linalg.norm(M)

3.715234169608681

In [118]:
np.linalg.matrix_rank(A)

3

In [119]:
np.linalg.cholesky(M)

array([[0.88310943, 0.        , 0.        ],
       [1.11629672, 0.04310207, 0.        ],
       [1.29309623, 0.06712701, 0.16370958]])

In [120]:
np.linalg.svd(A)

(array([[-0.45710668,  0.45668111, -0.76321416],
        [-0.57862223,  0.49899802,  0.64513354],
        [-0.67546266, -0.73650753, -0.03615051]]),
 array([1.927486  , 0.12402169, 0.02606741]),
 array([[-0.03622696, -0.37537922, -0.57626059, -0.72505295],
        [-0.49083223, -0.80048593,  0.20227636,  0.27819107],
        [ 0.11420497, -0.07680926,  0.79171606, -0.59518337],
        [-0.86297657,  0.4608829 ,  0.01391732, -0.20655436]]))

In [121]:
np.linalg.eig(M)

(array([3.71520227e+00, 6.79509868e-04, 1.53813786e-02]),
 array([[-0.45710668, -0.76321416, -0.45668111],
        [-0.57862223,  0.64513354, -0.49899802],
        [-0.67546266, -0.03615051,  0.73650753]]))